Improve the HTTP output client
SekoiaLab/graylog-http-plugin pull request #2
Opened 2019-10-11 09:51 UTC by squioc

Set, as a option, the raising ot HTTP errors as exceptions.
Fix the verification of the status code

2019-10-11 10:15 UTC, clslgrnc requested changes

2019-10-11 10:15 UTC, clslgrnc commented on src/main/java/com/plugin/HttpOutput.java
> +        this.raise_exception_on_http_error = conf.getBoolean(CK_GZIP_REQUEST);
```suggestion
        this.raise_exception_on_http_error = conf.getBoolean(CK_RAISE_EXCEPTION);
```

2019-10-14 09:06 UTC, squioc commented on src/main/java/com/plugin/HttpOutput.java
> +        this.raise_exception_on_http_error = conf.getBoolean(CK_GZIP_REQUEST);
FIXED

2019-10-14 09:22 UTC, clslgrnc approved these changes

2019-10-14 10:12 UTC, merged